version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumeMounts:
        - name: data
          mountPath: /mnt/db
          subPath: data
    ports:
      - '27017:27017'
