version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
    networks:
        clusternetwork:
          ipv4_address: 172.16.0.13
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment: 
      - MONGO_INITDB_DATABASE=todo
      - MONGO_INITDB_ROOT_USERNAME=usertodo
      - MONGO_INITDB_ROOT_PASSWORD=usertodoPassword1
    ports:
        - 27017:27017
    volumes:
      - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
    command: ["-f", "/etc/mongod.conf"]
    networks:
      clusternetwork:
        ipv4_address: 172.16.0.14
networks:
  clusternetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24