version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - db-data:/mnt/db/data
      - mongo-config:/mnt/db/config
    ports:
      - '27017:27017'
volumes:
  db-data:
  mongo-config:
